[package]
name = "rust-chat"
version = "0.2.1"
authors = ["Nikita Baksalyar <nikita.baksalyar@gmail.com>"]

[dependencies]
mio-websocket = { git = "https://github.com/nbaksalyar/mio-websocket" }
env_logger = "0.3"
